// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/booth-token': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/booth-token.post').default>>>>
    }
    '/api/guests': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/guests.get').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/messages.get').default>>>>
    }
    '/api/photo-booth-gallery': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/photo-booth-gallery.get').default>>>>
    }
    '/api/rsvp-status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rsvp-status.get').default>>>>
    }
    '/api/rsvp': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rsvp.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rsvp.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}