// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/06/2026, 12.50.00
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/wedding-fixed/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/wedding-fixed/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/wedding-fixed/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/wedding-fixed/plugins/**/*.{js,ts,mjs}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/wedding-fixed/composables/**/*.{js,ts,mjs}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/wedding-fixed/utils/**/*.{js,ts,mjs}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/wedding-fixed/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/wedding-fixed/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/wedding-fixed/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/wedding-fixed/app.config.{js,ts,mjs}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/wedding-fixed/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;