// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/06/2026, 22.30.36
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/undangan-nikah/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/undangan-nikah/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/undangan-nikah/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/undangan-nikah/plugins/**/*.{js,ts,mjs}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/undangan-nikah/composables/**/*.{js,ts,mjs}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/undangan-nikah/utils/**/*.{js,ts,mjs}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/undangan-nikah/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/undangan-nikah/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/undangan-nikah/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/undangan-nikah/app.config.{js,ts,mjs}","C:/Users/ogi-developer/OneDrive/Pictures/wedding-invitation-fixed/undangan-nikah/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;